### DISCUSSION TITLE
Values files not taken into account ?

### DISCUSSION THREAD

**Discussion by qlemaire-dvt** [werf/nelm#279] [Q&A] [answered]
Hi there,

I just started using the tool, and I've been playing around a bit.
Wanted to test on a real-life use case, but it seems like my values are not getting taken into account ?

Before opening an issue, I wanted to check if it was a "user-issue" or not.

This is how I proceeded : 

1. Create Chart.yaml
```
apiVersion: v2
name: mychart
version: 1.0.0
dependencies:
- name: vault
  version: 0.29.0
  repository: https://helm.releases.hashicorp.com
```

2. Create Chart.lock
```
nelm chart dependency download
```

3. Re-used my existing values.yaml
```
global:
  openshift: true

injector:
  enabled: false
ui:
  enabled: true
  
server:
  image:
    repository: "redacted.com/ocp-platform-mirror/hashicorp/vault"
    tag: "1.18.1-ubi"
  readinessProbe:
    path: "/v1/sys/health?uninitcode=204"
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  logLevel: debug

dev:
  enabled: true
```

4. Plan release (I love this !)
```
nelm release plan install --values values.yaml -r vault -n vault-dvp
```
Also tried with the `--no-default-values=false` and without the `--values` parameter.

This isn't showing any of the values I defined in values.yaml, and I can't figure out what I did wrong.

**Comment by ilya-lesikov** [comment, marked as answer]
Your `vault` chart is a subchart of `mychart`. Thus you should wrap your values for `vault` chart in a `vault` key in values.yaml file:
```yaml
global:
  openshift: true

vault:
  injector:
    enabled: false
  ui:
    enabled: true
    
  server:
    image:
      repository: "redacted.com/ocp-platform-mirror/hashicorp/vault"
      tag: "1.18.1-ubi"
    readinessProbe:
      path: "/v1/sys/health?uninitcode=204"
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
    logLevel: debug

  dev:
    enabled: true
```

Btw, `--values values.yaml` not needed. It is a default, since values.yaml is a values-file of the root chart.
