### ISSUE TITLE
namespaceSlug does not change ns

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [werf/nelm#110]
```
configVersion: 1
project: eventrouter
deploy:
  helmRelease: >-
    [[ project ]]
  helmReleaseSlug: false
  namespaceSlug: false
```
namespaceSlug has no effect
