### ISSUE TITLE
Nested chart dependencies are not pulled

### ISSUE THREAD

**Issue by d-enk** [werf/nelm#354]
### Before proceeding

- [x] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

2.36.3

### How to reproduce

[test.zip](https://github.com/user-attachments/files/20506352/test.zip)

Init
```bash
git init; git add .; git commit -m-
```

Update deps
```bash
helm dep up .helm/charts/nested; helm dep up .helm
```

Render
```bash
werf render --dev
```

### Result

```
Error: chart render: construct chart tree: render resources for chart "main": template: main/charts/nested/templates/configmap.yaml:4:12: executing "main/charts/nested/templates/configmap.yaml" at <include "common.names.fullname" .>: error calling include: template: no template "common.names.fullname" associated with template "gotpl"
```

`.helm/charts/nested/charts/common-2.*.tgz` not found because `*.tgz` in `.gitignore`

### Expected result

Nested chart dependency pulled

### Additional information

But if uncomment in `.helm/Chart.yaml`

```yaml
  # - name: common
  #   version: 2.x.x
  #   repository: oci://registry-1.docker.io/bitnamicharts
```

And update deps

```bash
helm dep up .helm
```

Dependency pulled:

```bash
werf render --dev
```
```
Pulled: registry-1.docker.io/bitnamicharts/common:2.31.1
Digest: sha256:e56d70ab6000aa08dadfd7c46a45851b51cb4616fd65a7dcee404e7037217fe1
---
# Source: main/charts/nested/templates/configmap.yaml
apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: recom-payments
    meta.helm.sh/release-namespace: recom-payments
    project.werf.io/env: ""
    project.werf.io/name: recom-payments
    werf.io/version: 2.36.3
  labels:
    app.kubernetes.io/managed-by: Helm
  name: recom-payments-nested
```

**Comment by d-enk** [comment]
How to enable in `werf-giterminism.yaml`?

**Comment by ilya-lesikov** [comment]
Helm recommends having all your deps in the top-level Chart.yaml (even if nested dependencies are specified in the nested charts, just specify the same dependencies in the top-level Chart.yaml). This way everything works, albeit the same nested dependencies now specified in two places.

If you still want to do this via multiple manual `helm dep up`, then try this:
```yaml
# werf-giterminism.yaml:
helm:
  allowUncommittedFiles:
    - "charts/**/*.tgz"
```
